pi = {'DT': 1,
      'NN': 0,
      'VBZ': 0,
      'VBD': 0}

A = {'DT': {'DT': 0,
            'NN': 1,
            'VBZ': 0,
            'VBD': 0},
     'NN': {'DT': 0,
            'NN': 0,
            'VBZ': 2/3,
            'VBD': 1/3},
     'VBZ': {'DT': .25,
             'NN': .25,
             'VBZ': .25,
             'VBD': .25},
     'VBD': {'DT': .25,
             'NN': .25,
             'VBZ': .25,
             'VBD': .25}}

B = {'DT': {'The': 2/3,
            'company': 0,
            'rises': 0,
            'fell': 0,
            'A': 1/3},
     'NN': {'The': 0,
            'company': 1,
            'rises': 0,
            'fell': 0,
            'A': 0},
     'VBZ': {'The': 0,
            'company': 0,
            'rises': 1,
            'fell': 0,
            'A': 0},
     'VBD': {'The': 0,
            'company': 0,
            'rises': 0,
            'fell': 1,
            'A': 0}}