small_training_sentences = ['The big company rises',
                            'The company fell',
                            'A company rises',
                            'The market is strong']
small_training_tags = [['DT', 'ADJ', 'NN', 'VBZ'],
                       ['DT', 'NN', 'VBD'],
                       ['DT', 'NN', 'VBZ'],
                       ['DT','NN','VBZ','ADJ']]


training_sentences = [
    "The big company rises",
    "The company fell",
    "A company rises",
    "The market is strong",
    "The market was weak",
    "A bank collapsed",
    "The bank rises",
    "The index is higher",
    "The stock fell sharply",
    "The firm gained value",
    "The company is growing",
    "The stock is falling",
    "The dollar strengthened",
    "The dollar weakened",
    "The price rose quickly",
    "A price fell",
    "The economy improved",
    "The economy slowed",
    "A firm reported profit",
    "The firm posted loss",
    "The market closed higher",
    "The market opened lower",
    "The stock surged",
    "The stock dropped",
    "A company posted gains",
    "The company reported losses",
    "The index gained slightly",
    "The index slipped",
    "The bond rose",
    "The bond fell",
    "The share rose",
    "The share fell",
    "The company is stable",
    "The company was unstable",
    "The prices are rising",
    "The prices were falling",
    "The earnings rose",
    "The earnings dropped",
    "The sales improved",
    "The sales declined",
    "The profit increased",
    "The profit decreased",
    "The firm expanded",
    "The firm contracted",
    "A company merged",
    "The company split",
    "The chairman spoke",
    "The board decided",
    "The report was released",
    "The report is final",
    "The fund gained",
    "The fund fell",
    "The economy is strong",
    "The economy was weak",
    "The government intervened",
    "The bank supported",
    "The policy shifted",
    "The rates rose",
    "The rates fell",
    "The investors reacted",
    "The investors sold",
    "The traders bought",
    "The traders sold",
    "The stock is steady",
    "The stock is volatile",
    "The company grows fast",
    "The company grew slowly",
    "The market remains stable",
    "The market became volatile",
    "The deal is final",
    "The deal was canceled",
    "The contract ended",
    "The contract started",
    "The chairman announced results",
    "The board approved plan",
    "The stock price rose",
    "The stock price dropped",
    "The new fund launched",
    "The new fund collapsed",
    "The merger was approved",
    "The merger is pending",
    "The dollar gained strength",
    "The dollar lost ground",
    "The yen strengthened",
    "The yen weakened",
    "The index advanced",
    "The index retreated",
    "The rate climbed",
    "The rate slipped",
    "The market rallied",
    "The market tumbled",
    "The bond yields rose",
    "The bond yields fell",
    "The company cut jobs",
    "The company hired workers",
    "The government raised taxes",
    "The government lowered taxes",
    "The bank increased lending",
    "The bank reduced lending",
    "The firm issued stock",
]

training_tags = [
    ['DT','ADJ','NN','VBZ'],
    ['DT','NN','VBD'],
    ['DT','NN','VBZ'],
    ['DT','NN','VBZ','ADJ'],
    ['DT','NN','VBD','ADJ'],
    ['DT','NN','VBD'],
    ['DT','NN','VBZ'],
    ['DT','NN','VBZ','JJR'],
    ['DT','NN','VBD','RB'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBZ','VBG'],
    ['DT','NN','VBZ','VBG'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD','RB'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD','JJR'],
    ['DT','NN','VBD','JJR'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','RB'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBZ','ADJ'],
    ['DT','NN','VBD','ADJ'],
    ['DT','NNS','VBP','VBG'],
    ['DT','NNS','VBD','VBG'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD','VBN'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBZ','ADJ'],
    ['DT','NN','VBD','ADJ'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBZ','RB'],
    ['DT','NN','VBD','RB'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBD','JJ'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBD','JJ'],
    ['DT','NN','VBZ','JJ'],
    ['DT','NN','VBD','JJ'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','NN','VBD'],
    ['DT','NN','NN','VBD'],
    ['DT','NN','VBD','VBN'],
    ['DT','NN','VBZ','VBG'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD','NN'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NN','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NNS','VBD'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','NNS'],
    ['DT','NN','VBD','VBG']
]
